#!/bin/bash 

usage() {
    printf "Usage:\n\n"
    printf "./restler-cli set [--api_spec=STRING] [--grammar_file=STRING] [--dictionary_file=STRING]  \ \n"
    printf "                  [--settings_file=STRING] [--token_refresh_command=STRING] [--token_refresh_interval=INT_SECS] \n\n"
    printf "OR \n\n"
    printf "./restler-cli run [--all] | [--compile] [--test] [--fuzzlean] [--fuzz] \n"
    exit 1
}


if [ ${1} = "set" ]; then
    echo "hiii"
elif [ ${1} = "run" ]; then
    echo "byeee"
else
    usage
fi